// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYK3iztd6WEk7E_5uFuxptRPbFxAR-34g',
    appId: '1:1003402792197:web:ab3e5d8c3d8ea912097b6c',
    messagingSenderId: '1003402792197',
    projectId: 'fasum-ef164',
    authDomain: 'fasum-ef164.firebaseapp.com',
    storageBucket: 'fasum-ef164.firebasestorage.app',
    measurementId: 'G-7RLP5JHE94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyhICCvjBuIlsBXEtEpUWESahYCpjIC0',
    appId: '1:1003402792197:android:271d9781eb78de8e097b6c',
    messagingSenderId: '1003402792197',
    projectId: 'fasum-ef164',
    storageBucket: 'fasum-ef164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgj13sPMruBUo_36Pgi_vWiedPvhph0yk',
    appId: '1:1003402792197:ios:47f8b9231f6e3070097b6c',
    messagingSenderId: '1003402792197',
    projectId: 'fasum-ef164',
    storageBucket: 'fasum-ef164.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgj13sPMruBUo_36Pgi_vWiedPvhph0yk',
    appId: '1:1003402792197:ios:47f8b9231f6e3070097b6c',
    messagingSenderId: '1003402792197',
    projectId: 'fasum-ef164',
    storageBucket: 'fasum-ef164.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYK3iztd6WEk7E_5uFuxptRPbFxAR-34g',
    appId: '1:1003402792197:web:5e19b52951db95ae097b6c',
    messagingSenderId: '1003402792197',
    projectId: 'fasum-ef164',
    authDomain: 'fasum-ef164.firebaseapp.com',
    storageBucket: 'fasum-ef164.firebasestorage.app',
    measurementId: 'G-NEQWG743X9',
  );
}
